logging:
  level:
    org.springframework.web: INFO

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/hillel
    username: postgres
    password: nk299359
    driver-class-name: org.postgresql.Driver

server:
  port: 8080
